version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 -w 2
    volumes:
      - static_volume:/home/app/web/staticfiles
      # - media_volume:/home/app/web/mediafiles
    restart: always
    # ports:
      # - 8000:8000
    expose:
      - 8000 
    env_file:
      - .env
    networks:
      - net-backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/app/web/staticfiles
      # - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    networks:
      - net-backend

networks:
  net-backend:


volumes:
  static_volume:
  # media_volume: